[platformio]
default_envs = nodeA1

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:nodeA1]
build_flags =
  -DSIM_NODE_ID=\"nodeA1\"
  -DDEFAULT_DEST_ID=\"nodeA2\"
  -DGATEWAY_ID=\"A\"
  -DENABLE_BLUETOOTH=1

[env:nodeA2]
build_flags =
  -DSIM_NODE_ID=\"nodeA2\"
  -DDEFAULT_DEST_ID=\"nodeA3\"
  -DGATEWAY_ID=\"A\"
  -DENABLE_BLUETOOTH=1

[env:nodeA3]
build_flags =
  -DSIM_NODE_ID=\"nodeA3\"
  -DDEFAULT_DEST_ID=\"nodeA1\"
  -DGATEWAY_ID=\"A\"
  -DENABLE_BLUETOOTH=1

[env:nodeB1]
build_flags =
  -DSIM_NODE_ID=\"nodeB1\"
  -DDEFAULT_DEST_ID=\"nodeB2\"
  -DGATEWAY_ID=\"B\"
  -DENABLE_BLUETOOTH=1

[env:nodeB2]
build_flags =
  -DSIM_NODE_ID=\"nodeB2\"
  -DDEFAULT_DEST_ID=\"nodeB3\"
  -DGATEWAY_ID=\"B\"
  -DENABLE_BLUETOOTH=1

[env:nodeB3]
build_flags =
  -DSIM_NODE_ID=\"nodeB3\"
  -DDEFAULT_DEST_ID=\"nodeB1\"
  -DGATEWAY_ID=\"B\"
  -DENABLE_BLUETOOTH=1

[env:nodeA1_lora]
build_flags =
  -DSIM_NODE_ID=\"nodeA1\"
  -DDEFAULT_DEST_ID=\"nodeA2\"
  -DGATEWAY_ID=\"A\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=1
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:nodeA2_lora]
build_flags =
  -DSIM_NODE_ID=\"nodeA2\"
  -DDEFAULT_DEST_ID=\"nodeA3\"
  -DGATEWAY_ID=\"A\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=1
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:nodeA3_lora]
build_flags =
  -DSIM_NODE_ID=\"nodeA3\"
  -DDEFAULT_DEST_ID=\"nodeA1\"
  -DGATEWAY_ID=\"A\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=1
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:nodeB1_lora]
build_flags =
  -DSIM_NODE_ID=\"nodeB1\"
  -DDEFAULT_DEST_ID=\"nodeB2\"
  -DGATEWAY_ID=\"B\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=1
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:nodeB2_lora]
build_flags =
  -DSIM_NODE_ID=\"nodeB2\"
  -DDEFAULT_DEST_ID=\"nodeB3\"
  -DGATEWAY_ID=\"B\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=1
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:nodeB3_lora]
build_flags =
  -DSIM_NODE_ID=\"nodeB3\"
  -DDEFAULT_DEST_ID=\"nodeB1\"
  -DGATEWAY_ID=\"B\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=1
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:gatewayA_lora]
build_flags =
  -DSIM_NODE_ID=\"gatewayA\"
  -DGATEWAY_ID=\"A\"
  -DDEFAULT_DEST_ID=\"nodeA1\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=0
lib_ignore =
  BluetoothSerial
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:gatewayB_lora]
build_flags =
  -DSIM_NODE_ID=\"gatewayB\"
  -DGATEWAY_ID=\"B\"
  -DDEFAULT_DEST_ID=\"nodeB1\"
  -DENABLE_LORA=1
  -DENABLE_BLUETOOTH=0
lib_ignore =
  BluetoothSerial
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0
