[platformio]
default_envs = node_a

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:node_a]
build_flags =
  -DSIM_NODE_ID=\"NODE_A\"
  -DDEFAULT_DEST_ID=\"NODE_B\"

[env:node_b]
build_flags =
  -DSIM_NODE_ID=\"NODE_B\"
  -DDEFAULT_DEST_ID=\"NODE_C\"

[env:node_c]
build_flags =
  -DSIM_NODE_ID=\"NODE_C\"
  -DDEFAULT_DEST_ID=\"NODE_A\"
